version: '3.8'

services:
  app:
    container_name: server-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:4173"
    environment:
      - NODE_ENV=production
